trigger:
- main

pool:
  name: MyHostpool # Replace with your agent pool name

variables:
  imageRepository: 'mansoordocker'
  containerRegistry: 'Mansoor'
  dockerfilePath: '$(System.DefaultWorkingDirectory)/project/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- checkout: self

- script: |
    sudo docker build -t $(imageRepository):$(tag) -f $(dockerfilePath) .
    sudo docker tag $(imageRepository):$(tag) $(containerRegistry)/$(imageRepository):$(tag)
    sudo docker push $(containerRegistry)/$(imageRepository):$(tag)
  displayName: 'Build and push Docker image'