version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'password'
      WORDPRESS_DB_NAME: 'wordpress'
    depends_on:
      - mysql
    volumes:
      - wordpress-data:/var/www/html

volumes:
  mysql-data:
  wordpress-data:





















